How to swap two rows of an array? (★★★)

In [3]:
# importing library
import numpy as np

# defining an array of numbers
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]


In [4]:
# Swapping row 1 with row 3
a[[0, 2]] = a[[2, 0]]
print(a)

[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


75. How to compute averages using a sliding window over an array? (★★★)

In [7]:
def averages(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n

x= np.arange(20)
b=averages(x,5)
print(b)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
