13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [49]:
import numpy as np

x=np.random.uniform(size=(10,10))

# finding the maximum and minimum number

a, b = x.max(), x.min()

print(a, b)

0.9934797454824772 0.010500773357144944


 Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [50]:
x= np.ones([5,5])
b=x[1:-1, 1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
