In [2]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [17]:
x=np.zeros(10)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,49)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z = np.arange(50)
Z = Z[::-1]

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
nz = np.arange(0,9)
nz.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.84700078 0.25724505 0.92255401]
  [0.58540672 0.45360271 0.18378163]
  [0.93067747 0.08889344 0.48398346]]

 [[0.12222199 0.41792995 0.95974227]
  [0.96021404 0.49564228 0.53945919]
  [0.12010491 0.77598096 0.89829699]]

 [[0.75375636 0.87617302 0.55404707]
  [0.99889143 0.88944143 0.08688808]
  [0.23999709 0.2793196  0.0436625 ]]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [12]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


How to ignore all numpy warnings (not recommended)? (★☆☆)

In [14]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [15]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it (★★☆)

In [16]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.20574094 0.23404758 0.62052047 0.65064446 0.68136082 0.70731473
 0.72290006 0.77353594 0.93960546 0.99278641]
